---
driver:
  name: vagrant
  provider: virtualbox
  vagrant_binary: <%= File.join(File.dirname(__FILE__), 'bin', 'vagrant-wrapper') %>

provisioner:
  name: ansible_push
  ansible_playbook_bin: <%= Dir.glob(File.join(Dir.pwd, 'venv/bin/ansible-playbook')).first || 'ansible-playbook' %>
  hosts: all
  require_ansible_repo: false
  playbook: tests/playbook.yml
  roles_path: roles
  ansible_version: latest
  ansible_host_key_checking: false
  ansible_galaxy_role_file: requirements.yml
  idempotency_test: false
  ansible_verbosity: 2
  require_windows_support: true
  extra_vars:
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_scheme: http
    ansible_winrm_server_cert_validation: ignore
    ansible_user: vagrant
    ansible_password: vagrant
    ansible_host: 127.0.0.1
    ansible_port: 55985

platforms:
  - name: win11
    driver:
      box: stromweld/windows-11
  - name: win11-disk
    driver:
      box: stromweld/windows-11
    provisioner:
      extra_vars:
        ansible_connection: winrm
        ansible_winrm_transport: basic
        ansible_winrm_scheme: http
        ansible_winrm_server_cert_validation: ignore
        ansible_user: vagrant
        ansible_password: vagrant
        ansible_host: 127.0.0.1
        ansible_port: 55985
        install_drive: 'D:'
  - name: win11-baseline
    driver:
      box: stromweld/windows-11-tomcat112


suites:
  - name: default
  - name: upgrade
    provisioner:
      playbook: tests/playbook-upgrade.yml
      extra_vars:
        upgrade_step: 1
  - name: downgrade
    provisioner:
      playbook: tests/playbook-downgrade.yml
      extra_vars:
        downgrade_step: 1
  - name: idempotence
  - name: no-autostart
    provisioner:
      extra_vars:
        tomcat_auto_start: false
  - name: upgrade-baseline
    provisioner:
      playbook: tests/playbook-upgrade.yml
      extra_vars:
        upgrade_step: 2
  - name: upgrade-candidate-aws
    provisioner:
      playbook: tests/playbook-upgrade.yml
      extra_vars:
        upgrade_step: 2
        tomcat_candidate_enabled: true
        tomcat_candidate_delegate: localhost
  - name: upgrade-candidate-aws-disk
    provisioner:
      playbook: tests/playbook-upgrade.yml
      extra_vars:
        upgrade_step: 2
        tomcat_candidate_enabled: true
        tomcat_candidate_delegate: localhost
        install_drive: 'D:'
